version: '3'

services:
    web:
        build: .
        command: sh launcher.sh
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
    db:
        image: postgres